
USE parking;
CREATE TABLE ALLOWED_PLATES (
	LICENSE_PLATE varchar(50),
	PENALTIES int
	)
CREATE TABLE PARKED_VEHICLES (LICENSE_PLATE varchar(50),
	ENTRANCE_TIME DATETIME,
	PARKING_TIME DATETIME,
	PARKING_SLOT_ID int,
	PARKED_PROPERLY BIT,
	UNPARKING_TIME DATETIME,
	EXIT_TIME DATETIME
	);

GO

CREATE OR ALTER PROCEDURE INSERT_PLATE
    @NUMBER VARCHAR(50),
    @RESULT BIT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM [parking].[dbo].ALLOWED_PLATES WHERE LICENSE_PLATE = @NUMBER)
    BEGIN
        INSERT INTO PARKED_VEHICLES (LICENSE_PLATE, ENTRANCE_TIME, PARKING_TIME, PARKING_SLOT_ID, PARKED_PROPERLY, UNPARKING_TIME, EXIT_TIME)
        VALUES (@NUMBER, GETDATE(), NULL, NULL, NULL, NULL, NULL);
        SET @RESULT = 1;
    END
    ELSE
    BEGIN
        SET @RESULT = 0;
    END
END;
GO
CREATE OR ALTER PROCEDURE PARK
	@NUMBER VARCHAR(50),
	@ID INT,
	@LEGALLY BIT
AS
BEGIN
	UPDATE PARKED_VEHICLES 
		SET PARKING_TIME = GETDATE(), PARKING_SLOT_ID = @ID, PARKED_PROPERLY = @LEGALLY
		WHERE LICENSE_PLATE=@NUMBER;
END;
GO
CREATE OR ALTER PROCEDURE UNPARK
	@NUMBER VARCHAR(50)
AS
BEGIN
	UPDATE PARKED_VEHICLES 
		SET UNPARKING_TIME = GETDATE(), PARKING_SLOT_ID = NULL
		WHERE LICENSE_PLATE=@NUMBER;
END;
GO
CREATE OR ALTER PROCEDURE EXITING
	@NUMBER VARCHAR(50)
AS
BEGIN
	DECLARE @INCREMENT_VALUE INT
	DECLARE @LEGALLY BIT
	SELECT @LEGALLY = PARKED_PROPERLY FROM PARKED_VEHICLES WHERE LICENSE_PLATE=@NUMBER;
	IF @LEGALLY IS NULL OR @LEGALLY = 1
		SET @INCREMENT_VALUE = 0
	ELSE
		SET @INCREMENT_VALUE = 1
	UPDATE PARKED_VEHICLES 
		SET EXIT_TIME = GETDATE()
		WHERE LICENSE_PLATE=@NUMBER;
	UPDATE ALLOWED_PLATES
		SET PENALTIES=PENALTIES+@INCREMENT_VALUE
		WHERE LICENSE_PLATE=@NUMBER;
END;
GO


